wip

diff --git a/.github/workflows/node-daily.yml b/.github/workflows/node-daily.yml
--- a/.github/workflows/node-daily.yml
+++ b/.github/workflows/node-daily.yml
@@ -2,6 +2,17 @@ name: nodejs nightly build
 
 on:
   workflow_dispatch:
+    inputs:
+      nodeVersion:
+        description: 'nodejs version'
+        required: true
+        type: string
+        default: nightly
+      npmVersion:
+        description: 'npm version'
+        required: true
+        type: string
+        default: git
 
 # used by setup-ccache-action's post hook to cleanup old caches
 permissions:
@@ -11,52 +22,80 @@ concurrency:
   group: ${{ github.workflow }}
   cancel-in-progress: true
 
-env:
-  # used for both the ccache key and artifact names
-  key_prefix: nodejs-nightly 
-
 jobs:
   build-nodejs:
     name: build nodejs
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.build-nodejs.outputs.version }}
+      version: ${{ steps.build-nodejs.outputs.nodeVersion }}
     steps:
       - name: setup ccache
         uses: Chocobo1/setup-ccache-action@v1
         with:
-          override_cache_key: ${{ env.key_prefix }}
-      - name: checkout npm/cli
-        uses: actions/checkout@v3
-        with:
-          repository: npm/cli
+          override_cache_key: nodejs-${{ input.nodeVersion }}
       - name: build nodejs
         id: build-nodejs
         run: |
+          echo "::group::setup"
           set -eo pipefail
-
+          npmDir="${RUNNER_TEMP}/npm"
           sourceDir="${RUNNER_TEMP}/src"
           targetDir="${RUNNER_TEMP}/build"
           sourceFile="${RUNNER_TEMP}/source.tgz"
           targetFile="${RUNNER_TEMP}/build.tgz"
-
-          echo "::group::finding latest nightly version"
-          version="$(curl -sSL https://nodejs.org/download/nightly/index.json | jq -r .[0].version)"
-          echo "version=${version}" >> $GITHUB_OUTPUT
           echo "::endgroup::"
 
-          echo "::group::extracting source"
+          echo "::group::finding nodejs version matching ${{ inputs.nodeVersion }}"
+          if [[ "${{ inputs.nodeVersion }}" == "nightly" ]]; then
+            nodeVersion=$(curl -sSL https://nodejs.org/download/nightly/index.json | jq -r .[0].version)
+            nodeUrl="https://nodejs.org/download/nightly/${version}/node-${version}.tar.gz"
+          else
+            nodeVersion=$(curl -sSL https://nodejs.org/download/release/index.json | jq -r 'map(select(.version | test("^v${{ inputs.nodeVersion }}"))) | .[0].version')
+            if [[ -z "$version" ]]; then
+              echo "::error ::unable to find released nodejs version matching: ${{ inputs.nodeVersion }}"
+              exit 1
+            fi
+            nodeUrl="https://nodejs.org/download/release/${version}/node-${version}.tar.gz"
+          fi
+          echo "nodeVersion=${nodeVersion}" >> $GITHUB_OUTPUT
+          echo "::endgroup::"
+
+          echo "::group::finding npm version matching ${{ inputs.npmVersion }}"
+          if [[ "${{ inputs.npmVersion }}" == "git" ]]; then
+            npmUrl="https://codeload.github.com/npm/cli/tar.gz/HEAD"
+            npmVersion=$(curl -sSL https://raw.githubusercontent.com/npm/cli/HEAD/package.json | jq -r '"\(.version)-git"')
+          else
+            npmVersion=$(curl -sSL https://registry.npmjs.org/npm |\
+              jq -r '.time | to_entries | map(select(.key | test("^[0-9]"))) | sort_by(.value | split(".") | "\(.[0])Z" | fromdate) | .[-1].key')
+            npmGitHead=$(npm show npm@$version --json | jq -r '.gitHead')
+            npmUrl="https://codeload.github.com/npm/cli/tar.gz/${npmGitHead}"
+          fi
+          echo "npmVersion=${npmVersion}" >> $GITHUB_OUTPUT
+          echo "::endgroup::"
+
+          echo "::group::extracting source from $nodeUrl"
           mkdir -p "$sourceDir"
-          curl -sSL "https://nodejs.org/download/nightly/${version}/node-${version}.tar.gz" |\
-            tar xz -C "$sourceDir" --strip=1
+          curl -sSL "$nodeUrl" | tar xz -C "$sourceDir" --strip=1 
           echo "::endgroup::"
 
-          echo "::group::packing npm release"
+          echo "::group::extracting npm source from $npmUrl"
+          mkdir -p "$npmDir"
+          curl -sSL "$npmUrl" | tar xz -C "$npmDir" --strip=1
+          echo "::endgroup::"
+
+          echo "::group::packing npm release $npmVersion"
+          pushd "$npmDir" >/dev/null
           node . run resetdeps
           npmtarball="$(node . pack --loglevel=silent --json | jq -r .[0].filename)"
+          mv "$npmtarball" "npm.tgz"
+          popd >/dev/null
+          echo "npm=${npmDir}/npm.tgz" >> $GITHUB_OUTPUT
+          echo "::endgroup::"
+
+          echo "::group::updating nodejs bundled npm"
           rm -rf "${sourceDir}/deps/npm"
           mkdir -p "${sourceDir}/deps/npm"
-          tar xfz "$npmtarball" -C "${sourceDir}/deps/npm" --strip=1
+          tar xfz "${npmDir}/npm.tgz" -C "${sourceDir}/deps/npm" --strip=1
           echo "::endgroup::"
 
           echo "::group::packing nodejs source"
@@ -79,27 +118,26 @@ jobs:
       - name: upload artifacts
         uses: actions/upload-artifact@v3
         with:
-          name: ${{ env.key_prefix }}-${{ steps.build-nodejs.outputs.version }}
+          name: nodejs-${{ steps.build-nodejs.outputs.nodeVersion }}
           path: |
             ${{ steps.build-nodejs.outputs.source }}
             ${{ steps.build-nodejs.outputs.build }}
+            ${{ steps.build-nodejs.outputs.npm }}
 
   test-nodejs:
     name: test nodejs
     runs-on: ubuntu-latest
     needs:
       - build-nodejs
-    outputs:
-      version: ${{ needs.build-nodejs.outputs.version }}
     steps:
       - name: setup ccache
         uses: Chocobo1/setup-ccache-action@v1
         with:
-          override_cache_key: ${{ env.key_prefix }}
+          override_cache_key: nodejs-${{ input.nodeVersion }}
       - name: download artifacts
         uses: actions/download-artifact@v3
         with:
-          name: ${{ env.key_prefix }}-${{ needs.build-nodejs.outputs.version }}
+          name: nodejs-${{ needs.build-nodejs.outputs.nodeVersion }}
       - name: test nodejs
         run: |
           set -e
@@ -113,10 +151,6 @@ jobs:
     needs:
       - build-nodejs
     steps:
-      - name: checkout npm/cli
-        uses: actions/checkout@v3
-        with:
-          repository: npm/cli
       - name: download artifacts
         uses: actions/download-artifact@v3
         with:
@@ -128,6 +162,9 @@ jobs:
           set -e
           mkdir -p "${RUNNER_TEMP}/node"
           tar xf "${RUNNER_TEMP}/build.tgz" -C "${RUNNER_TEMP}/node"
+
+          mkdir -p "${RUNNER_TEMP}/npm"
+          tar xf "${RUNNER_TEMP}/npm.tgz" -C "${RUNNER_TEMP}/npm" --strip=1
 
           echo "${RUNNER_TEMP}/node/bin" >> $GITHUB_PATH
           echo "cache=$(npm config get cache)" >> $GITHUB_OUTPUT
@@ -141,9 +178,11 @@ jobs:
       - name: test npm
         run: |
           set -e
+          pushd "${RUNNER_TEMP}/npm" >/dev/null
           node . run resetdeps
           node . link
           node . run test -ws -iwr --if-present --ignore-scripts
+          popd >/dev/null
 
   generate-matrix:
     name: generate matrix
@@ -153,7 +192,7 @@ jobs:
     steps:
       - name: install dependencies
         run: |
-          npm install --no-audit --no-fund citgm npm-package-arg
+          npm install --no-save --no-audit --no-fund citgm npm-package-arg
       - name: generate matrix
         id: generate-matrix
         uses: actions/github-script@v6
@@ -245,9 +284,9 @@ jobs:
       - name: download artifacts
         uses: actions/download-artifact@v3
         with:
-          name: ${{ env.key_prefix }}-${{ needs.build-nodejs.outputs.version }}
+          name: nodejs-${{ needs.build-nodejs.outputs.nodeVersion }}
           path: ${{ runner.temp }}
-      - name: install nodejs ${{ needs.build-nodejs.outputs.version }}
+      - name: install nodejs ${{ needs.build-nodejs.outputs.nodeVersion }}
         id: install
         run: |
           set -e
