wip

diff --git a/.github/workflows/node-daily.yml b/.github/workflows/node-daily.yml
--- a/.github/workflows/node-daily.yml
+++ b/.github/workflows/node-daily.yml
@@ -195,51 +195,6 @@ jobs:
             }
             core.setOutput('matrix', matrix)
 
-  npm-ls:
-    name: ${{ matrix.package }} - npm ls
-    runs-on: ubuntu-latest
-    needs:
-      - build-nodejs
-      - build-matrix
-    strategy:
-      fail-fast: false
-      matrix:
-        include: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
-    steps:
-      - name: checkout npm/cli
-        uses: actions/checkout@v3
-        with:
-          repository: npm/cli
-      - name: download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: ${{ env.key_prefix }}-${{ needs.build-nodejs.outputs.version }}
-          path: ${{ runner.temp }}
-      - name: install nodejs ${{ needs.build-nodejs.outputs.version }}
-        id: install
-        run: |
-          mkdir -p "${RUNNER_TEMP}/node" "${RUNNER_TEMP}/node-src"
-          tar xf "${RUNNER_TEMP}/build.tgz" -C "${RUNNER_TEMP}/node"
-          tar xf "${RUNNER_TEMP}/source.tgz" -C "${RUNNER_TEMP}/node-src"
-
-          echo "${RUNNER_TEMP}/node/bin" >> $GITHUB_PATH
-          echo "cache=$(npm config get cache)" >> $GITHUB_OUTPUT
-      - name: setup npm cache
-        uses: actions/cache@v3
-        with:
-          path: ${{ steps.install.outputs.cache }}
-          key: npm-${{ matrix.package }}
-      - run: node --version
-      - run: npm --version
-      - name: setup tap problem matcher
-        run: |
-          echo "::add-matcher::.github/matchers/tap.json"
-      - name: npm ls
-        run: |
-          npm i -g citgm
-          echo "require('child_process').execSync('npm ls')" > "${RUNNER_TEMP}/citgm-npm-ls.js"
-          citgm --tap --nodedir="${RUNNER_TEMP}/node-src" --customTest="${RUNNER_TEMP}/citgm-npm-ls.js" ${{ matrix.package }}
-
   citgm:
     name: ${{ matrix.package }} - citgm ${{ matrix.flaky && '(flaky)' || '' }} ${{ matrix.knownFailure && '(known failure)' || '' }}
     runs-on: ubuntu-latest
@@ -283,4 +238,11 @@ jobs:
       - name: citgm
         run: |
           npm i -g citgm@latest
+
+          echo "require('child_process').execSync('npm ls')" > "${RUNNER_TEMP}/citgm-npm-ls.js"
+          citgm --tap --nodedir="${RUNNER_TEMP}/node-src" --customTest="${RUNNER_TEMP}/citgm-npm-ls.js" ${{ matrix.package }}
+          if [ $? -ne 0 ]; then
+            echo "::error ::invalid package tree found!"
+          fi
+
           citgm --tap --nodedir="${RUNNER_TEMP}/node-src" ${{ matrix.package }}
